import {
    FaBrain,
    FaBolt,
    FaFire,
    FaClock,
    FaArrowRight,
    FaExclamationTriangle,
} from "react-icons/fa";

interface Props {
    priorityTask: string;
    productivity: number;
    momentum: number;
    energy: string;
    delayRisk: string;
    burnoutRisk: string;
    estimatedFinish: string;
    recommendedBreak: string;
    nextTask: string | null;
}
import { useNavigate } from "react-router-dom";
export default function AIDailyBrief({
    priorityTask,
    productivity,
    momentum,
    energy,
    delayRisk,
    burnoutRisk,
    estimatedFinish,
    recommendedBreak,
    nextTask,
}: Props) {
    const navigate = useNavigate();
    const riskColor =
        delayRisk === "High"
            ? "text-red-400"
            : delayRisk === "Medium"
            ? "text-yellow-400"
            : "text-green-400";

    return (
        <section className="overflow-hidden rounded-3xl border border-cyan-500/30 bg-gradient-to-br from-slate-900 via-slate-900 to-cyan-950 p-8 shadow-2xl">

            {/* Header */}

            <div className="mb-8 flex items-center gap-4">

                <div className="rounded-2xl bg-gradient-to-r from-cyan-500 to-blue-600 p-4 text-white">

                    <FaBrain size={32} />

                </div>

                <div>

                    <h2 className="text-3xl font-bold text-white">
                        AI Daily Brief
                    </h2>

                    <p className="text-slate-400">
                        Live intelligence generated by NEXUS AI
                    </p>

                </div>

            </div>

            {/* Grid */}

            <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">

                <div className="rounded-2xl bg-slate-800/70 p-5">

                    <p className="text-sm text-slate-400">
                        🎯 Priority Mission
                    </p>

                    <h3 className="mt-3 text-xl font-bold text-white">
                        {priorityTask}
                    </h3>

                </div>

                <div className="rounded-2xl bg-slate-800/70 p-5">

                    <div className="flex items-center gap-2">

                        <FaFire className="text-orange-400" />

                        <span className="text-slate-400">
                            Momentum
                        </span>

                    </div>

                    <h3 className="mt-3 text-3xl font-bold text-white">
                        {momentum}%
                    </h3>

                </div>

                <div className="rounded-2xl bg-slate-800/70 p-5">

                    <div className="flex items-center gap-2">

                        <FaBolt className="text-cyan-400" />

                        <span className="text-slate-400">
                            Energy
                        </span>

                    </div>

                    <h3 className="mt-3 text-3xl font-bold text-white">
                        {energy}
                    </h3>

                </div>

                <div className="rounded-2xl bg-slate-800/70 p-5">

                    <p className="text-slate-400">
                        Productivity
                    </p>

                    <h3 className="mt-3 text-3xl font-bold text-green-400">
                        {productivity}%
                    </h3>

                </div>

            </div>

            {/* Footer */}

            <div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-4">

                <div className="rounded-2xl bg-slate-800/60 p-5">

                    <div className="flex items-center gap-2">

                        <FaClock className="text-cyan-400" />

                        <span className="text-slate-400">
                            Finish
                        </span>

                    </div>

                    <h3 className="mt-2 text-white">
                        {estimatedFinish}
                    </h3>

                </div>

                <div className="rounded-2xl bg-slate-800/60 p-5">

                    <p className="text-slate-400">
                        Recommended Break
                    </p>

                    <h3 className="mt-2 text-white">
                        {recommendedBreak}
                    </h3>

                </div>

                <div className="rounded-2xl bg-slate-800/60 p-5">

                    <div className="flex items-center gap-2">

                        <FaExclamationTriangle className={riskColor} />

                        <span className="text-slate-400">
                            Delay Risk
                        </span>

                    </div>

                    <h3 className={`mt-2 font-bold ${riskColor}`}>
                        {delayRisk}
                    </h3>

                    <p className="mt-3 text-sm text-slate-400">
                        Burnout: {burnoutRisk}
                    </p>

                </div>

                <div
                    onClick={() => navigate("/tasks")}
                    className="
                        cursor-pointer
                        rounded-2xl
                        bg-gradient-to-r
                        from-blue-600
                        to-cyan-600
                        p-5
                        text-white
                        transition-all
                        duration-300
                        hover:scale-[1.02]
                        hover:shadow-xl
                    "
                >

                    <div className="flex items-center gap-2">

                        <FaArrowRight />

                        <span>
                            Next Best Task
                        </span>

                    </div>

                    <h3 className="mt-3 text-xl font-bold">

                        {nextTask ?? "You're all caught up 🎉"}

                    </h3>

                </div>

            </div>

        </section>
    );
}